---
- hosts: dev_server
  tasks:
  - name: Create networks
    import_role: 
      name: vms
      tasks_from: create_networks

  - name: Prepare image
    import_role:
      name: vms
      tasks_from: prepare_image

  - name: Create VM
    import_role:
      name: vms
      tasks_from: create_helper
