---
- hosts: dev_server
  become: yes
  tasks:
  - name: Prepare image
    import_role:
      name: vms
      tasks_from: prepare_image

  - name: Create cloud-init 
    import_role:
      name: vms
      tasks_from: create_cloud_init
