---
# Setup repository for RHEL 8
- name: resigtr rhms
  redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    pool_ids:
      - "{{ rhsm_8_poolid }}"

- name: enabled common repos
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items: 
  - "{{ repos_r8_common }}"
  - "{{ repos_r8_ansible }}"


- name: install modules
  dnf:
    name: "{{ item }}"
    state: latest 
  with_items:
  - dnsmasq
  - git
  - ansible
  - firewalld

- name: copy resolv.conf
  copy:
    remote_src: yes
    src: /etc/resolv.conf
    dest: /etc/dnsmasq-resolv.conf

#- name: Configure dnsmasq
#resolv-file=

- name: Configure dnsmasq
  ansible.builtin.lineinfile:
    path: /etc/dnsmasq.conf
    regexp: '^resolv-file= '
    insertafter: '^#resolv-file= '
    line: resolv-file=/etc/dnsmasq-resolv.conf

- name: Start dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: true

- name: Start firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: open dns port 
  ansible.posix.firewalld:
    service: dns
    permanent: true
    state: enabled
    immediate: yes

