---
- name: set resolv.conf
  lineinfile:
    dest: /etc/resolv.conf
    line: nameserver 192.168.100.1
    state: present

- name: Copy hosts
  copy:
    src: /etc/hosts
    dest: /etc/hosts
    backup: yes
