---
- name: stop public network
  community.libvirt.virt_net:
    command: stop
    name: "{{ public_network_name }}"
  ignore_errors: true

#- name: stop private network
#  community.libvirt.virt_net:
#    command: stop
#    name: private

- name: undefine public network
  community.libvirt.virt_net:
    command: undefine
    name: "{{ public_network_name}}"
  ignore_errors: true

#- name: undefine private network
#  community.libvirt.virt_net:
#    command: undefine
#    name: private
