---
- name: Stop VMs
  community.libvirt.virt:
    name: "{{ hostvars[item].inventory_hostname_short }}"
    command: destroy
  become: true
  with_inventory_hostnames: cephs

- name: Undefine VMs
  community.libvirt.virt:
    name: "{{ hostvars[item].inventory_hostname_short }}"
    command: undefine
  become: true
  with_inventory_hostnames: cephs

