---
- name: Register subscription manager
  with_inventory_hostnames: helper
  redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    pool_ids: "{{ rhsm_poolid  }}"  

- name: Enable repos
  with_items: "{{ rhel8_repos }}"
  rhsm_repository:
    name: "{{ item }}"
    state: enabled

- name: Update dns
  yum:
    name: '*'
    state: latest

- name: Install packages
  yum:
    name: "{{ helper_packages }}"
    state: latest

- name: Git clone helper node
  git:
    repo: https://github.com/RedHatOfficial/ocp4-helpernode
    dest: ~/ocp4-helpernode

- name: Copy vars.yaml
  template:
    src: vars.yaml.j2
    dest: ~/ocp4-helpernode/vars.yaml

#- name: Execute playbook
#  shell: |
#    cd ~/ocp4-helpernode/
#    ansible-playbook -e @vars.yaml tasks/main.yml

- name: Copy install-config.yaml
  become: false
  template:
    src: install-config.yaml.j2
    dest: ~/install-config.yaml

#- name: Generate ignition file
#  become: false
#  shell: |
#    openshift-install create manifests
#    sed -i 's/mastersSchedulable: true/mastersSchedulable: false/g' manifests/cluster-scheduler-02-config.yml
#    openshift-install create ignition-configs
#    sudo cp ~/*.ign /var/www/html/ignition/
#    sudo restorecon -vR /var/www/html/
#    sudo chmod o+r /var/www/html/ignition/*.ign
