---
# Setup repository for RHEL 7
- name: resigtr rhms
  redhat_subscription: 
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    pool_ids: 
      - "{{ rhsm_poolid }}"

#- name: disabled repos
#  community.general.rhsm_repository:
#    name: '*'
#    state: disabled

- name: enabled common repos
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items: "{{ repos_r7_common }}"
  when: inventory_hostname in groups['all']

- name: enabled ansible repos
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items: "{{ repos_r7_ansible  }}"
  when: inventory_hostname in groups['ansible']

- name: enabled mon repos
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items: "{{ repos_r7_mon }}"
  when: inventory_hostname in groups['mon']

- name: enabled osd repos
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items: "{{ repos_r7_osd }}"
  when: inventory_hostname in groups['osd']

- name: enabled others repos
  community.general.rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items: "{{ repos_r7_others }}"
  when: inventory_hostname in groups['others']

- name: install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - firewalld


- name: enable firewalld
  service:
    name: firewalld
    enabled: true
    state: started

- name: setup firewalld
  ansible.posix.firewalld:
    port: 6789/tcp
    zone: public
    permanent: yes
    state: enabled

- name: setup firewalld
  ansible.posix.firewalld:
    port: 6800-7300/tcp
    zone: public
    permanent: yes
    state: enabled

- name: setup firewalld
  ansible.posix.firewalld:
    port: 8080/tcp
    zone: public
    permanent: yes
    state: enabled

- name: setup firewalld
  ansible.posix.firewalld:
    port: 80/tcp
    zone: public
    permanent: yes
    state: enabled

- name: setup firewalld
  ansible.posix.firewalld:
    port: 443/tcp
    zone: public
    permanent: yes
    state: enabled

